from tkinter import *

root = Tk()
root.title("Calculator")
root.geometry("300x330")
root.minsize(width=300, height=330)
root.maxsize(width=300, height=330)

f0 = Frame(root, padx=4, pady=5)
f0.pack(fill="x", side="top")
in_out_value = IntVar()
in_out = Entry(f0, textvariable=in_out_value, width=22, border=6, borderwidth=6)
in_out.pack(side="right")

f1 = Frame(root, pady=6)
f1.pack(side="top", fill="both")
button_clear = Button(f1, text="C", padx=3, pady=3, width=4, bg="light grey", borderwidth=6, font="lucida 10 bold")
button_clear.pack(side="left", padx=4)
button_delete = Button(f1, text="x", padx=3, pady=3, width=4, bg="light grey", borderwidth=6, font="lucida 10 bold")
button_delete.pack(side="right", padx=4)

f2 = Frame(root, pady=6)
f2.pack(side="top", fill="both")
button_7 = Button(f2, text="7", width=5, bg="light grey", borderwidth=6, font="monospace 10 bold", padx=3, pady=3)
button_7.pack(side="left", padx=4)
button_8 = Button(f2, text="8", width=5, bg="light grey", borderwidth=6, font="monospace 10 bold", padx=3, pady=3)
button_8.pack(side="left", padx=4)
button_9 = Button(f2, text="9", width=5, bg="light grey", borderwidth=6, font="monospace 10 bold", padx=3, pady=3)
button_9.pack(side="left", padx=4)
button_divide = Button(f2, text="/", width=5, bg="light grey", borderwidth=6, font="monospace 11 bold", padx=3, pady=3)
button_divide.pack(side="right", padx=4)

f3 = Frame(root, pady=6)
f3.pack(side="top", fill="both")
button_4 = Button(f3, text="4", width=5, bg="light grey", borderwidth=6, font="monospace 10 bold", padx=3, pady=3)
button_4.pack(side="left", padx=4)
button_5 = Button(f3, text="5", width=5, bg="light grey", borderwidth=6, font="monospace 10 bold", padx=3, pady=3)
button_5.pack(side="left", padx=4)
button_6 = Button(f3, text="6", width=5, bg="light grey", borderwidth=6, font="monospace 10 bold", padx=3, pady=3)
button_6.pack(side="left", padx=4)
button_multiply = Button(f3, text="*", width=5, bg="light grey", borderwidth=6, font="monospace 11 bold", padx=3, pady=3)
button_multiply.pack(side="right", padx=4)

f4 = Frame(root, pady=6)
f4.pack(side="top", fill="both")
button_1 = Button(f4, text="1", width=5, bg="light grey", borderwidth=6, font="monospace 10 bold", padx=3, pady=3)
button_1.pack(side="left", padx=4)
button_2 = Button(f4, text="2", width=5, bg="light grey", borderwidth=6, font="monospace 10 bold", padx=3, pady=3)
button_2.pack(side="left", padx=4)
button_3 = Button(f4, text="3", width=5, bg="light grey", borderwidth=6, font="monospace 10 bold", padx=3, pady=3)
button_3.pack(side="left", padx=4)
button_addition = Button(f4, text="+", width=5, bg="light grey", borderwidth=6, font="monospace 11 bold", padx=3, pady=3)
button_addition.pack(side="right", padx=4)

f5 = Frame(root, pady=6)
f5.pack(side="top", fill="both")
button_dot = Button(f5, text=".", width=5, bg="light grey", borderwidth=6, font="monospace 10 bold", padx=3, pady=3)
button_dot.pack(side="left", padx=4)
button_0 = Button(f5, text="0", width=5, bg="light grey", borderwidth=6, font="monospace 10 bold", padx=3, pady=3)
button_0.pack(side="left", padx=4)
button_exp = Button(f5, text="^", width=5, bg="light grey", borderwidth=6, font="monospace 10 bold", padx=3, pady=3)
button_exp.pack(side="left", padx=4)
button_subtraction = Button(f5, text="-", width=5, bg="light grey", borderwidth=6, font="monospace 11 bold", padx=3, pady=3)
button_subtraction.pack(side="right", padx=4)


root.mainloop()